{{- $fullName := include "chatgpt-next-web.fullname" . -}}
{{- $servicePort := .Values.service.port | default 80 -}}

{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{- include "chatgpt-next-web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.kong_plugins }}
    konghq.com/plugins: {{ . }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  tls: {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .http.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
---
# {{- if .Values.ingress.public_endpoints -}}
# # Reuse block using Yaml definication https://yaml.org/type/merge.html
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "chatgpt-next-web.fullname" . }}-public
#   {{- with .Values.ingress.annotations }}
#   annotations: {{- toYaml . | nindent 4 }}
#   {{- end }}
# spec:
#   {{- with .Values.ingress.tls }}
#   tls: {{- tpl (toYaml .) $ | nindent 4 }}
#   {{- end }}
#   rules:
#   - http:
#       paths:
#       {{- range .Values.ingress.public_endpoints }}
#       - path: {{ . }}
#         pathType: Prefix
#         backend:
#           service:
#             name: {{ $fullName }}
#             port:
#               number: {{ $servicePort }}
#       {{- end }}
#     {{- with (first .Values.ingress.tls) }}
#     host: {{ first .hosts }}
#     {{- end }}
# {{- end }}

# ---
# apiVersion: configuration.konghq.com/v1beta1
# kind: TCPIngress
# metadata:
#   name: {{ $fullName }}-rpc
#   annotations:
#     kubernetes.io/ingress.class: kong
# spec:
#   rules:
#   - port: 6066
#     backend:
#       serviceName: {{ $fullName }}
#       servicePort: 6066